<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Testcontainers.Azurite" Version="4.12.0" />
    <PackageReference Include="Testcontainers.CosmosDb" Version="4.12.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UnitTests\Hydration\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\infrastructure\CascadeEsdm.DistributedLocks\CascadeEsdm.DistributedLocks.csproj" />
    <ProjectReference Include="..\..\src\infrastructure\CascadeEsdm.Logging.OpenTelemetry\CascadeEsdm.Logging.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\infrastructure\CascadeEsdm.Storage.CosmosDb\CascadeEsdm.Storage.CosmosDb.csproj" />
    <ProjectReference Include="..\..\src\write\CascadeEsdm.WriteModel\CascadeEsdm.WriteModel.csproj" />
  </ItemGroup>

</Project>
