<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>CascadeEsdm.Storage.CosmosDb</PackageId>
        <Description>Provides a CosmosDb implementation of the IPartitionedContainer interface for EventStream hydration and writing.</Description>
        <PackageIcon>icon.jpg</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="docs\README.md" Pack="true" PackagePath="\" /> 
        <None Include="docs\icon.jpg" Pack="true" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.57.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>    
    <ItemGroup>
        <ProjectReference Include="..\..\shared\CascadeEsdm.SharedKernel.Abstractions\CascadeEsdm.SharedKernel.Abstractions.csproj" />
    </ItemGroup>    
</Project>
