<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Cascade.SharedKernel</PackageId>
    <Description>Core implementation for the Cascade Event Sourcing framework</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\Cascade.SharedKernel.Abstractions\Cascade.SharedKernel.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="Cascade.SharedKernel.Abstractions" Version="$(CascadeVersion)" />
  </ItemGroup>

</Project>
