<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Cascade.Views</PackageId>
    <Description>View/Query implementation for the Cascade Event Sourcing framework</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\Cascade.Views.Abstractions\Cascade.Views.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="Cascade.Views.Abstractions" Version="$(CascadeVersion)" />
  </ItemGroup>

</Project>
