<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>CascadeEsdm.Commands</PackageId>
    <Description>Command handling implementation for the Cascade Event Sourcing framework</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\shared\CascadeEsdm.SharedKernel\CascadeEsdm.SharedKernel.csproj" />
    <ProjectReference Include="..\CascadeEsdm.Commands.Abstractions\CascadeEsdm.Commands.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="CascadeEsdm.SharedKernel" Version="$(CascadeVersion)" />
    <PackageReference Include="CascadeEsdm.Commands.Abstractions" Version="$(CascadeVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Composition\" />
  </ItemGroup>
</Project>
