<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CascadeEsdm.WriteModel</RootNamespace>
    <PackageId>CascadeEsdm.WriteModel.Abstractions</PackageId>
    <Description>Command abstractions for the Cascade Event Sourcing framework</Description>
    <PackageIcon>icon.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" /> 
    <None Include="docs\icon.jpg" Pack="true" PackagePath="\" />
    <None Include="packaging\CascadeEsdm.WriteModel.Abstractions.targets" Pack="true" PackagePath="build\" />
    <None Include="packaging\CascadeEsdm.WriteModel.Abstractions.targets" Pack="true" PackagePath="buildTransitive\" />    
  </ItemGroup>
  
  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\shared\CascadeEsdm.SharedKernel.Abstractions\CascadeEsdm.SharedKernel.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="CascadeEsdm.SharedKernel.Abstractions" Version="$(CascadeVersion)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CascadeEsdm.WriteModel.Tests"/>
    <InternalsVisibleTo Include="CascadeEsdm.TestDomain"/>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
  </ItemGroup>  
</Project>
