<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\read\CascadeEsdm.ReadModel\CascadeEsdm.ReadModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UnitTests\" />
  </ItemGroup>

</Project>
