<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\tools\CascadeEsdm.EventExtractor\CascadeEsdm.EventExtractor.csproj" />
  </ItemGroup>

</Project>
