<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
        <RootNamespace>CascadeEsdm.TestDomain</RootNamespace>
        <CascadeEventsEnabled>false</CascadeEventsEnabled>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CascadeEsdm.WriteModel.Tests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\write\CascadeEsdm.WriteModel.Abstractions\CascadeEsdm.WriteModel.Abstractions.csproj" />
      <ProjectReference Include="..\CascadeEsdm.OtherTestDomain.Schema\CascadeEsdm.OtherTestDomain.Schema.csproj" />
    </ItemGroup>

</Project>
