<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CascadeEsdm.ReadModel</RootNamespace>
    <PackageId>CascadeEsdm.ReadModel.Abstractions</PackageId>
    <Description>View/Query abstractions for the Cascade Event Sourcing framework</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
