<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>CascadeEsdm.SignalR</PackageId>
        <Description>Provides an Azure SignalR implementation of IViewNotificationService for real-time view change notifications.</Description>
        <PackageIcon>icon.jpg</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="docs\README.md" Pack="true" PackagePath="\" /> 
        <None Include="docs\icon.jpg" Pack="true" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.33.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\read\CascadeEsdm.ReadModel.Abstractions\CascadeEsdm.ReadModel.Abstractions.csproj"/>
        <ProjectReference Include="..\..\read\CascadeEsdm.ReadModel\CascadeEsdm.ReadModel.csproj"/>
    </ItemGroup>

</Project>
