<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>CascadeEsdm.ReadModel</PackageId>
    <Description>View/Query implementation for the Cascade Event Sourcing framework</Description>
    <PackageIcon>icon.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" /> 
    <None Include="docs\icon.jpg" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\CascadeEsdm.ReadModel.Abstractions\CascadeEsdm.ReadModel.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="CascadeEsdm.ReadModel.Abstractions" Version="$(CascadeVersion)" />
  </ItemGroup>

</Project>
