<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <AssemblyName>CascadeEsdm.OtherTestDomain.Schema</AssemblyName>
    <RootNamespace>CascadeEsdm.OtherTestDomain.Schema</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\src\shared\CascadeEsdm.SharedKernel.Abstractions\CascadeEsdm.SharedKernel.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
    <PackageReference Include="CascadeEsdm.SharedKernel.Abstractions" Version="1.0.116" />
  </ItemGroup>
</Project>